# Generated by Django 6.0.5 on 2026-05-08 06:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "place_type",
                    models.CharField(
                        choices=[
                            ("restaurant", "Restaurant"),
                            ("hospital", "Hospital"),
                            ("school", "School"),
                            ("park", "Park"),
                            ("hotel", "Hotel"),
                        ],
                        max_length=100,
                    ),
                ),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("address", models.TextField(blank=True)),
            ],
        ),
    ]
