version: "3.8"
services:
  db:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_DB: gisdb
      POSTGRES_USER: gisuser
      POSTGRES_PASSWORD: gispass
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  osrm-data-downloader:
    image: alpine
    volumes:
      - osrm-data:/data
    command: >
      sh -c "if [ ! -f /data/map.osm.pbf ]; then
        # Option 1: Monaco (Small, 500KB - Recommended for fast local testing)
        wget -O /data/map.osm.pbf http://download.geofabrik.de/europe/monaco-latest.osm.pbf;
        
        # Option 2: India (Large, 1.5GB - Requires 16GB+ RAM to process)
        # wget -O /data/map.osm.pbf https://download.geofabrik.de/asia/india-latest.osm.pbf;
      fi"

  osrm:
    image: osrm/osrm-backend
    ports:
      - "5000:5000"
    depends_on:
      osrm-data-downloader:
        condition: service_completed_successfully
    volumes:
      - osrm-data:/data
    command: >
      sh -c "if [ ! -f /data/map.osrm ]; then
        osrm-extract -p /opt/car.lua /data/map.osm.pbf &&
        osrm-partition /data/map.osrm &&
        osrm-customize /data/map.osrm;
      fi && osrm-routed --algorithm mld /data/map.osrm"

volumes:
  pgdata:
  osrm-data: