version: "3.8"
services:
  db:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_DB: gisdb
      POSTGRES_USER: gisuser
      POSTGRES_PASSWORD: gispass
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    dns:
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      - db

  osrm-data-downloader:
    image: alpine
    volumes:
      - osrm-data:/data
    command: >
      sh -c "if [ ! -f /data/map.osm.pbf ]; then
        # Option 1: Monaco (Small, 500KB - Recommended for fast local testing)
        wget -O /data/map.osm.pbf http://download.geofabrik.de/europe/monaco-latest.osm.pbf;
        
        # Option 2: India (Large, 1.5GB - Requires 16GB+ RAM to process)
        # wget -O /data/map.osm.pbf https://download.geofabrik.de/asia/india-latest.osm.pbf;
      fi"

  osrm-car:
    image: osrm/osrm-backend
    ports:
      - "5001:5000"
    depends_on:
      osrm-data-downloader:
        condition: service_completed_successfully
    volumes:
      - osrm-data:/data
    command: >
      sh -c "if [ ! -f /data/car.osrm ]; then
        ln -sf /data/map.osm.pbf /data/car.osm.pbf &&
        osrm-extract -p /opt/car.lua /data/car.osm.pbf &&
        osrm-partition /data/car.osrm &&
        osrm-customize /data/car.osrm;
      fi && osrm-routed --algorithm mld /data/car.osrm"

  osrm-foot:
    image: osrm/osrm-backend
    depends_on:
      osrm-data-downloader:
        condition: service_completed_successfully
    volumes:
      - osrm-data:/data
    command: >
      sh -c "if [ ! -f /data/foot.osrm ]; then
        ln -sf /data/map.osm.pbf /data/foot.osm.pbf &&
        osrm-extract -p /opt/foot.lua /data/foot.osm.pbf &&
        osrm-partition /data/foot.osrm &&
        osrm-customize /data/foot.osrm;
      fi && osrm-routed --algorithm mld /data/foot.osrm"

  osrm-bicycle:
    image: osrm/osrm-backend
    depends_on:
      osrm-data-downloader:
        condition: service_completed_successfully
    volumes:
      - osrm-data:/data
    command: >
      sh -c "if [ ! -f /data/bicycle.osrm ]; then
        ln -sf /data/map.osm.pbf /data/bicycle.osm.pbf &&
        osrm-extract -p /opt/bicycle.lua /data/bicycle.osm.pbf &&
        osrm-partition /data/bicycle.osrm &&
        osrm-customize /data/bicycle.osrm;
      fi && osrm-routed --algorithm mld /data/bicycle.osrm"

volumes:
  pgdata:
  osrm-data: